### ISSUE TITLE
calculating mean per chromosome

### ISSUE THREAD

**Issue by IsmailM** [brentp/mosdepth#46]
Hey, 

What's the best/quickest way of getting a single value for the mean depth per chromosome (and mean depth for entire genome)?

Many Thanks, 
Ismail Moghul

**Comment by brentp** [comment]
you can get this by finding the value closest to 0.5 for each chromosome (and then for "total" for the entire genome) in the .dist.txt output.

**Comment by brentp** [comment]
please re-open if your issue is not resolved.

**Comment by TMiguelT** [comment]
I'm confused. For the following `dist.txt` output, how would I calculate the mean coverage for the chromosome?
```
chrUn_KI270466v1    4   0.06
chrUn_KI270466v1    3   0.11
chrUn_KI270466v1    2   0.24
chrUn_KI270466v1    1   0.64
chrUn_KI270466v1    0   1.00
```

You seem to be saying I should just choose `1`, since it's closest to 0.5, but I don't really see how that makes sense. I want a precise mean, and I'm not even sure you can calculate that from the `dist.txt. output

**Comment by brentp** [comment]
this is mostly an oversight as we never need a precise mean. what you get from the 0.5 value is actually the median. You can get a mean using the script below.
I'll open a new issue to track the feature of outputting the mean depths.

```

## run as python $script xx.mosdepth.global.dist.txt
import sys

pairs = [map(float, x.split()[1:]) for x in open(sys.argv[1]) if x.startswith("total")]

total = 0
lastp = 0
for dp, p in pairs:
    total += dp * (p - lastp)
    lastp = p
print(total)
```
